"""add user theme and notifications preferences

Revision ID: 68aaa27e4a13
Revises: 6aa3b3d3c396
Create Date: 2025-08-26 20:26:48.216621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aaa27e4a13'
down_revision = '6aa3b3d3c396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=False, server_default='light'))
        batch_op.add_column(sa.Column('notifications', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notifications')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
