"""Add UserTransaction model for personal savings tracking

Revision ID: a70ff4bdefc9
Revises: 5d5e0f67c28e
Create Date: 2025-10-28 18:57:17.370158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70ff4bdefc9'
down_revision = '5d5e0f67c28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount != 0', name='check_user_transaction_amount_non_zero'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme')
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('theme', sa.VARCHAR(length=10), server_default=sa.text("'light'"), nullable=False))

    op.drop_table('user_transaction')
    # ### end Alembic commands ###
